# Turn on validation, so we can use import:
version: ~> 1.0

rvm:
- 2.6.5

services:
- mysql

import:
- land-of-apps/land-of-apps:travis/ruby-imports.yml

jobs:
  include:
  - stage: rspec
    workspaces:
      create:
        name: appmaps
        paths:
        - vendor/bundle
        - public/assets
        - public/packs-test
        - node_modules
        - app/javascript/packages/*/node_modules
        - tmp/appmap
    install:
    - bundle config path vendor/bundle
    - bundle install --jobs 3 --retry 3
    - bundle update appmap
    - nvm install 10.15
    - npm install
    - sudo apt-get install sphinxsearch
    script:
    - cp config/database.example.yml config/database.yml
    - cp config/config.example.yml config/config.yml
    - bundle exec rails assets:precompile
    - bundle exec rake db:create db:structure:load
    - bundle exec rake ts:index
    - bundle exec rake ts:start

    # testing
    - APPMAP=true bundle exec rspec spec/controllers/admin/admin_base_controller_spec.rb || true
    #- APPMAP=true bundle exec rspec || true
    after_script:
    - true
  - stage: admin
    workspaces:
      use:
        - appmaps
    before_script:
    - nvm install 10.15
    - npm install
    - sudo apt-get install sphinxsearch
    script:
    - cp config/database.example.yml config/database.yml
    - cp config/config.example.yml config/config.yml
    - bundle exec rails assets:precompile
    - bundle exec rake db:create db:structure:load
    - bundle exec rake ts:index
    - bundle exec rake ts:start

    # testing
    - APPMAP=true bundle exec cucumber features/admin/act_as_person/admin_creates_new_listing.feature || true
    #- APPMAP=true bundle exec cucumber features/admin || true
    after_script:
    - true
  - stage: admin_2
    workspaces:
      use:
      - appmaps
    before_script:
    - nvm install 10.15
    - npm install
    - sudo apt-get install sphinxsearch
    script:
    - cp config/database.example.yml config/database.yml
    - cp config/config.example.yml config/config.yml
    - bundle exec rails assets:precompile
    - bundle exec rake db:create db:structure:load
    - bundle exec rake ts:index
    - bundle exec rake ts:start

    # testing
    - APPMAP=true bundle exec ccumber features/admin2/admin_add_listing_fields.feature || true
    #- APPMAP=true bundle exec cucumber features/admin2 features/common features/communities features/conversations features/email features/feedback features/homepage features/infos features/invitations || true
    after_script:
    - true
  - stage: rest_of_cucumber
    workspaces:
      use:
      - appmaps
    before_script:
    - nvm install 10.15
    - npm install
    - sudo apt-get install sphinxsearch
    script:
    - cp config/database.example.yml config/database.yml
    - cp config/config.example.yml config/config.yml
    - bundle exec rails assets:precompile
    - bundle exec rake db:create db:structure:load
    - bundle exec rake ts:index
    - bundle exec rake ts:start

    # testing
    - APPMAP=true bundle exec cucumber features/listings/search.feature || true
    #- APPMAP=true bundle exec cucumber features/listings features/payments features/paypal features/people features/sessions features/settings features/step_definitions features/stripe features/support || true
    after_script:
    - true
  - stage: upload
    workspaces:
      use:
      - appmaps
    install:
    - true
    script:
    - true
